### ISSUE TITLE
Is that app maintained?

### ISSUE THREAD

**Issue by farfromrefug** [nikolaeu/Numi-extensions#105]
I would like to know if that app is maintained. Seems to be in preorder for quite sometime.

I actually really like it and would like to see some bugs fixed.

**Comment by nikolaeu** [comment]
You should expect new update v soon with massive cryptocurrency support and some fixes. A lot of improvements planned for coming year :)

**Comment by farfromrefug** [comment]
@nikolaeu great!!! is this repo the place to report bugs?

**Comment by nikolaeu** [comment]
It's better to mail issues to mail@numi.io
This is primarily for Numi extensions
