### ISSUE TITLE
Alfred workflow doesn't work in Alfred 4

### ISSUE THREAD

**Issue by omBratteng** [nikolaeu/Numi-extensions#112]
I just upgraded to Alfred 4, and the workflow no longer works.
It doesn't have any output
![](https://i.woof.no/git/3VzVk0OFV6u9Gpbl0CgV83WO.png)

**Comment by womeimingzi11** [comment]
+1 I met this problem too.

**Comment by samuelam** [comment]
A hack to get it working again:
Edit the "n" Script Filter and replace
`const alfred = Application('Alfred 3')`
with
`const alfred = Application('Alfred 4')`

**Comment by womeimingzi11** [comment]
Great! It works well after replace the Alfred 3 into Alfred 4, as @samuelam suggested.

**Comment by omBratteng** [comment]
Awesome, that worked. I've opened a pull request #113 that checks for Alfred 3 or 4

**Comment by omBratteng** [comment]
Fixed in #113
