### ISSUE TITLE
Numi plugins list

### ISSUE THREAD

**Issue by LukeeeeBennett** [nikolaeu/Numi-extensions#12]
Is there any current Numi plugins? If there is, is there a list?

**Comment by LukeeeeBennett** [comment]
I believe this is due to the NumiKit framework not being quite ready for use? Please feel free to close this if this is the case, I will get a plugins list together myself when I'm able to build some. :)

**Comment by igordot** [comment]
Have there been any updates on this front? I would also be curious to see the available plugins and how people distribute them.

**Comment by nikolaeu** [comment]
It's quite hard ATM to develop and distribute plugins via current plugin system. Beta 15 should introduce new JavaScript plugin architecture, so, it will be much easier to build/use new plugins.

**Comment by igordot** [comment]
Awesome! Looking forward to it.

It would be nice to also have some kind of a centralized repository. If it's just a GitHub repo (like Homebrew formulas), that might not be too much work.
