### ISSUE TITLE
Numi alfred package (development version) not working!

### ISSUE THREAD

**Issue by gbstan** [nikolaeu/Numi-extensions#35]
Numi is really great!

Some issues with the alfred package though:

I have just downloaded both numi (development version: http://numi.io/static/dev/Numi.zip) and the alfred package numi by nilolaeu from packal: http://www.packal.org/workflow/numi

When I try to use the alfred package (shortcut "n") anything I type after it leads to the error:
Failed to connect to localhost:15055: Connection refused

Any idea how to fix this (if possible without to have to explicitly authorise port 15055)?

**Comment by drreen** [comment]
Same issue here

**Comment by nikolaeu** [comment]
@gbstan @drreen can you try to disable and re-enable Alfred integration in Numi preferences ?

**Comment by gbstan** [comment]
Sure. It now works with the latest versions of Numi and the Numi Alfred workflow.   
    
  
  
Sent from my phone.
  

  
  
  
  
  

  
  
>

**Comment by yeastcapp** [comment]
I don't see the Alfred option in the Numi preferences. I'm using the Setapp version.

**Comment by nikolaeu** [comment]
@yeastcapp should be available v soon

**Comment by yeastcapp** [comment]
@nikolaeu Thanks dude!
