### ISSUE TITLE
Not understanding how to add custom units.

### ISSUE THREAD

**Issue by CarcajadaArtificial** [nikolaeu/numi-extensions#45]
Hi, 
Firstly, great product. I'm just trying to add new unit using JavaScript as you mention. I just don't know where to place the .js code. Do I write it inside the Numi editor? Do I place the .js inside the files of Numi? If that is the case, where do I place the file?
I'm sorry. I'm a little lost in this whole extension thing.
Thanks

**Comment by nikolaeu** [comment]
Hey @CarcajadaArtificial 
In preferences, open "Extensions" tab. There you will see button "Open extension folder".
