### ISSUE TITLE
Numi Alfred extension issue with using localhost

### ISSUE THREAD

**Issue by pruthvikar** [nikolaeu/Numi-extensions#60]
When using the numi extension for Alfred, I get really slow response times and sometimes an incorrect result of 1.

The slow response seems to be related to the lookup time and also appeared on curl requests.

However, when I changed the url from `http://localhost:15055` to `http://127.0.0.1:15055`, the performance issues were all fixed.

**Comment by siddharthalodha** [comment]
I was not able to get any data before. Now, it's working perfectly.
