### ISSUE TITLE
Move .alfredworkflow to it's own repo?

### ISSUE THREAD

**Issue by danielbayley** [nikolaeu/Numi-extensions#74]
I have made a bunch of improvements to my local copy of the workflow, including rewriting it from PHP into very simple javascript that runs natively through `osascript`… I would like to open some PRs, but that wouldn't be very useful as the workflow currently exists as basically just a binary blob as far as Git/Hub are concerned…

This way you could also utilise GitHub releases with it. @nikolaeu What do you think?

**Comment by danielbayley** [comment]
This is the Script Filter code for example:
~~~ js
#! /usr/bin/osascript -l JavaScript
const os = Application.currentApplication()
os.includeStandardAdditions = true
const se = Application('System Events')

const alfred = Application('Alfred 3')
const numi = Application('Numi')
const port = 15055

run = input => {
  const query = encodeURIComponent(input)
  let result
  try {
    result = os.doShellScript(`curl http://localhost:${port}/?q=${query}`)
  }
  catch (error) {
    numi.activate()
    delay(.25)
    se.processes.byName('Numi').visible = false

    alfred.runTrigger('numi', {
      inWorkflow: 'com.dmitrynikolaev.numi',
      withArgument: input
    })
  }
  const workings = `${input} = ${result}`
  items = [{
    title: result,
    arg: result,
    text: { copy: workings, largetype: workings },
    mods: {
      cmd: { subtitle: workings, arg: workings },
      alt: { arg: decodeURIComponent(input) }
    }
  }]
  return JSON.stringify({items})
}
~~~

**Comment by danielbayley** [comment]
p.s @nikolaeu Also, I have already [added] this workflow to _[homebrew-alfred]_… but using releases would enable better, _[versioned]_ downloads…

[homebrew-alfred]: https://github.com/danielbayley/homebrew-alfred
[added]: https://github.com/danielbayley/homebrew-alfred/blob/master/Casks/alfred-numi.rb#L2-L3
[versioned]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#adding-a-cask

**Comment by nikolaeu** [comment]
Great work @danielbayley, and good idea on releases! Can you please create PR with plugin sources and attach binary for the workflow ?

**Comment by danielbayley** [comment]
@nikolaeu Do you mean a PR here or a seperate repo?

**Comment by nikolaeu** [comment]
PR here. Actually workflow's binary already in the repo, would be great to have sources instead, and binary with release.

**Comment by danielbayley** [comment]
@nikolaeu Check out #79…

Exported binary is here: [numi.alfredworkflow.zip](https://github.com/nikolaeu/Numi-extensions/files/1862169/numi.alfredworkflow.zip), but the `.zip` extenstion needs to be removed (GitHub wouldn't let me upload otherwise…)

**Comment by nikolaeu** [comment]
Amazing work @danielbayley, thank you!
