### ISSUE TITLE
Alfred workflow produces an endless loop beetween numi and alfred

### ISSUE THREAD

**Issue by muescha** [nikolaeu/Numi-extensions#85]
when i start typing in alfred i got an endless loop in alfred starting numi and switching beetween the alfred and numi app

workaround:
not working: quit numi via activity app - it restarted numi
working: only thing was to import again the workflow to get the alfred settings page for workflows and remove there the workflow

**Comment by mrahmadt** [comment]
Same issue here.

Alfred 3.6.1

**Comment by nikolaeu** [comment]
Should be fixed now in 1.2.1
https://github.com/nikolaeu/Numi-extensions/releases
