### ISSUE TITLE
Loop between Alfred and Lumi in High Sierra

### ISSUE THREAD

**Issue by RoccellaRocks** [nikolaeu/Numi-extensions#89]
After having installed first Numi for Alfred, then Numi – via www.numi.io – and having tried Numi with a banale "2*2", an infinite loop takes place and I'm unable to use Numi at all.

**Comment by nikolaeu** [comment]
@RoccellaRocks can you please update Alfred extension to the latest version (see releases). Also, please make sure "Alfred integration" checked in Numi preferences.
