### ISSUE TITLE
Alfred integration doesn't work for Mojave

### ISSUE THREAD

**Issue by varunachar** [nikolaeu/Numi-extensions#99]
Integrated with Alfred, post that it went berserk. I tried a currency conversion on Alfred, it rapid (5-10 times a sec) kept switching between the Alfred spotlight and the Numi app.

**Comment by nikolaeu** [comment]
@varunachar did you enable Alfred integration in Numi settings ?

**Comment by varunachar** [comment]
It worked after I enabled it from within the app. Didn't notice it in the documentation. Apologies.


________________________________

**Comment by lihsai0** [comment]
[doesn't work](https://i.loli.net/2018/11/06/5be10a102d65b.png)
I enable alfred integration, but it doesn't work.

**Comment by lihsai0** [comment]
> ![doesn't work](https://camo.githubusercontent.com/9a31ad218fe302fc671f91432a77c7e8a2ea6866/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f30362f356265313061313032643635622e706e67)
> I enable alfred integration, but it doesn't work.

The workflow use `curl http://localhost:15055/?q=` to get result.

Check the `curl`, `/etc/hosts` and the port occupancy, if it doesn't work.
